services:

    dineromail.form.type.wrapper:
        class: %dineromail.form.type.wrapper.class%
        arguments:
            form.factory: @form.factory
            payment.bridge: @payment.bridge
            dineromail.api.endpoint: %dineromail.api.endpoint%
            dineromail.merchant: %dineromail.merchant%
            dineromail.seller_name: %dineromail.seller_name%
            dineromail.header_image: %dineromail.header_image%
            dineromail.url_redirect_enabled: %dineromail.url_redirect_enabled%
            dineromail.payment_methods_available: %dineromail.payment_methods_available%
            dineromail.country: %dineromail.country%
        tags:
            - { name: form.type, alias: dineromail_view }

    dineromail.routes.loader:
        class: %dineromail.routes.loader.class%
        arguments:
            dineromail.controller.route: %dineromail.controller.route%
            dineromail.controller.route.name: %dineromail.controller.route.name%
            dineromail.controller.process.route: %dineromail.controller.process.route%
            dineromail.controller.process.route.name: %dineromail.controller.process.route.name%
        tags:
            - { name: routing.loader }

    dineromail.manager:
            class: %dineromail.manager.class%
            arguments:
                payment.event.dispatcher: @payment.event.dispatcher
                payment.bridge: @payment.bridge
                dineromail.country: %dineromail.country%
                dineromail.merchant: %dineromail.merchant%
                dineromail.ipn_key: %dineromail.ipn_key%
                logger: @logger