services:

    paymentsuite.paylands.api.discovery_proxy:
        class: WAM\Paylands\DiscoveryProxy

    paymentsuite.paylands.api.request_factory:
        class: WAM\Paylands\RequestFactory
        public: false
        arguments:
            - '@paymentsuite.paylands.api.discovery_proxy'
            - "@=service('paymentsuite.paylands.settings_provider').getApiSignature()"

    paymentsuite.paylands.api.client_factory:
        class: WAM\Paylands\ClientFactory
        public: false
        arguments:
            - '@paymentsuite.paylands.api.request_factory'
            - '@paymentsuite.paylands.api.discovery_proxy'
            - "@=service('paymentsuite.paylands.settings_provider').getApiKey()"
            - '%paymentsuite.paylands.api_url%'

    paymentsuite.paylands.api.client_default:
        class: WAM\Paylands\Client
        factory: ['@paymentsuite.paylands.api.client_factory', 'create']
        public: false
        calls:
            - [setOperative, ['%paymentsuite.paylands.operative%']]
            - [setTemplates, ['%paymentsuite.paylands.fallback_template_uuid%', "@=service('paymentsuite.paylands.settings_provider').getI18nCardTemplates()"]]

    paymentsuite.paylands.api.adapter:
        class: PaymentSuite\PaylandsBundle\Services\PaylandsApiAdapter
        arguments:
            - '@paymentsuite.paylands.api.client'
            - '@paymentsuite.bridge'
            - '@paymentsuite.paylands.currency_service_resolver'
            - '@request_stack'
