services:

    paymentsuite.paylands.payment_controller:
        class: PaymentSuite\PaylandsBundle\Controller\PaymentController
        public: true
        arguments:
            - '@paymentsuite.paylands.manager'
            - '@paymentsuite.paylands.form_factory'
            - '@paymentsuite.paylands.routes'
            - '@paymentsuite.bridge'
            - '@router'