services:

    paymentsuite.paylands.form_factory:
        class: PaymentSuite\PaylandsBundle\Services\PaylandsFormFactory
        arguments:
            - '@form.factory'
            - '@router'

    paymentsuite.paylands.manager:
        class: PaymentSuite\PaylandsBundle\Services\PaylandsManager
        arguments:
            - '@paymentsuite.bridge'
            - '@paymentsuite.event_dispatcher'
            - '@paymentsuite.paylands.event_dispatcher'
            - '@paymentsuite.paylands.api.adapter'

    paymentsuite.paylands.view_renderer:
        class: PaymentSuite\PaylandsBundle\Services\PaylandsViewRenderer
        arguments:
            - '@paymentsuite.paylands.api.client'
            - '@paymentsuite.paylands.form_factory'
            - '@paymentsuite.paylands.currency_service_resolver'
            - '%paymentsuite.paylands.view_template%'
            - '%paymentsuite.paylands.scripts_template%'
            - '%paymentsuite.paylands.sandbox%'

    paymentsuite.paylands.currency_service_resolver:
        class: PaymentSuite\PaylandsBundle\Services\PaylandsCurrencyServiceResolver
        public: false
        arguments:
            - '@paymentsuite.bridge'
            - '@paymentsuite.paylands.settings_provider'

    paymentsuite.paylands.settings_provider_default:
        class: PaymentSuite\PaylandsBundle\Services\PaylandsSettingsProviderDefault
        arguments:
            - '%paymentsuite.paylands.api_key%'
            - '%paymentsuite.paylands.signature%'
            - '%paymentsuite.paylands.payment_services%'
            - '%paymentsuite.paylands.i18n_template_uuids%'
            - '%paymentsuite.paylands.validation_service%'
