language: php

sudo: false

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

before_script:
  - composer update --no-interaction

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

notifications:
  email: false
