language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  fast_finish: true

before_script:
  - composer update --no-interaction

script:
  - phpunit -c phpunit.xml.dist

notifications:
  email: false