language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_script:
  - composer update --no-interaction

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

notifications:
  email: false
