services:

    webpay.form.type.wrapper:
        class: %webpay.form.type.wrapper.class%
        arguments:
            form.factory: @form.factory
            payment.bridge: @payment.bridge
            webpay.kcc.cgi.uri: %webpay.kcc.cgi.uri%
        tags:
            - { name: form.type, alias: webpay_view }

    webpay.manager:
        class: %webpay.manager.class%
        arguments:
            payment.event.dispatcher: @payment.event.dispatcher
            payment.bridge: @payment.bridge
            webpay.kcc.path: %webpay.kcc.path%

    webpay.routes.loader:
        class: %webpay.routes.loader.class%
        arguments:
            webpay.controller.route.execute.name: %webpay.controller.route.execute.name%
            webpay.controller.route.execute.schemes: %webpay.controller.route.execute.schemes%
            webpay.controller.route.execute: %webpay.controller.route.execute%
            webpay.controller.route.confirmation.name: %webpay.controller.route.confirmation.name%
            webpay.controller.route.confirmation.schemes: %webpay.controller.route.confirmation.schemes%
            webpay.controller.route.confirmation: %webpay.controller.route.confirmation%
        tags:
            - { name: routing.loader }
