services:

    pagosonline.form.type:
        class: %pagosonline.form.type.class%
        arguments:
            router: @router
            payment.bridge: @payment.bridge
            pagosonline.controller.route.name: %pagosonline.controller.route.name%
        tags:
            - { name: form.type, alias: pagosonline_view }

    pagosonline.manager:
            class: %pagosonline.manager.class%
            arguments:
                payment.event.dispatcher: @payment.event.dispatcher
                payment.bridge: @payment.bridge
                logger: @logger
                pagosonline.account_id: %pagosonline.account_id%
                payment_comm.manager: @pagosonline_comm.manager

    pagosonline.twig.extension:
        class: %pagosonline.twig.extension.class%
        arguments:
            form.factory: @form.factory
            payment.bridge: @payment.bridge
        tags:
            - { name: twig.extension }

    pagosonline.routes.loader:
        class: %pagosonline.routes.loader.class%
        arguments:
          pagosonline.controller.route.name: %pagosonline.controller.route.name%
          pagosonline.controller.route: %pagosonline.controller.route%
          container: @service_container
        tags:
            - { name: routing.loader }