services:


    #
    # Controllers
    #
    paymentsuite.paypal_express_checkout.controller:
        class: PaymentSuite\FreePaymentBundle\Controller\FreePaymentController
        arguments:
            - @paymentsuite.paypal_express_checkout.manager
            - @paymentsuite.bridge
            - %paymentsuite.paypal_express_checkout.routes%
            - @router
            - @form.factory
