services:

    #
    # Services
    #
    paymentsuite.paypal_express_checkout.manager:
        class: PaymentSuite\PaypalExpressCheckoutBundle\Services\PaypalExpressCheckoutManager
        arguments:
            - @paymentsuite.event_dispatcher
            - @paymentsuite.bridge
            - @paymentsuite.paypal_express_checkout.requester

    paymentsuite.paypal_express_checkout.twig_extension:
        class: PaymentSuite\PaypalExpressCheckoutBundle\Twig\PaypalExpressCheckoutExtension
        arguments:
            - @form.factory
            - @paymentsuite.bridge
        tags:
            - { name: twig.extension }
