services:
    paymentsuite.stripe.form_type:
        class: PaymentSuite\StripeBundle\Form\Type\StripeType
        arguments:
            - '@paymentsuite.bridge'
        tags:
            - { name: form.type, alias: stripe_view }

    paymentsuite.stripe.transaction_factory:
        class: PaymentSuite\StripeBundle\Services\StripeTransactionFactory
        arguments:
            - '%paymentsuite.stripe.private_key%'

    paymentsuite.stripe.manager:
        class: PaymentSuite\StripeBundle\Services\StripeManager
        arguments:
            - '@paymentsuite.stripe.transaction_factory'
            - '@paymentsuite.bridge'
            - '@paymentsuite.event_dispatcher'

    paymentsuite.stripe.method_factory:
        class: PaymentSuite\StripeBundle\Services\StripeMethodFactory

    paymentsuite.stripe.template_render:
        class: PaymentSuite\StripeBundle\Services\StripeTemplateRender
        arguments:
            - '@paymentsuite.bridge'
            - '@form.factory'
            - '%paymentsuite.stripe.public_key%'
            - '%paymentsuite.stripe.view_template%'
            - '%paymentsuite.stripe.scripts_template%'
