services:

    #
    # Services
    #
    paymentsuite.freepayment.method_factory:
        class: PaymentSuite\FreePaymentBundle\Services\FreePaymentMethodFactory
        arguments:
            - 'paymentsuite.freepayment.settings_provider'

    paymentsuite.freepayment.manager:
        class: PaymentSuite\FreePaymentBundle\Services\FreePaymentManager
        arguments:
            - '@paymentsuite.freepayment.method_factory'
            - '@paymentsuite.bridge'
            - '@paymentsuite.event_dispatcher'

    paymentsuite.freepayment.settings_provider_default:
        class: PaymentSuite\FreePaymentBundle\Services\FreePaymentSettingsProviderDefault
