services:

    #
    # Controllers
    #
    paymentsuite.paypal_web_checkout.payment_controller:
        class: PaymentSuite\PaypalWebCheckoutBundle\Controller\PaymentController
        public: true
        arguments:
            - '@paymentsuite.paypal_web_checkout.manager'
            - '@templating'

    paymentsuite.paypal_web_checkout.process_controller:
        class: PaymentSuite\PaypalWebCheckoutBundle\Controller\ProcessController
        public: true
        arguments:
            - '@paymentsuite.paypal_web_checkout.manager'
            - '@paymentsuite.logger'
