services:

    #
    # Controllers
    #
    paymentsuite.redsys.payment_controller:
        class: PaymentSuite\RedsysBundle\Controller\PaymentController
        arguments:
            - '@paymentsuite.redsys.manager'
            - '@templating'
        tags:
            - { name: controller.service_arguments }

    paymentsuite.redsys.response_controller:
        class: PaymentSuite\RedsysBundle\Controller\ResponseController
        arguments:
            - '@paymentsuite.redsys.routes'
            - '@router'
        tags:
            - { name: controller.service_arguments }

    paymentsuite.redsys.result_controller:
        class: PaymentSuite\RedsysBundle\Controller\ResultController
        arguments:
            - '@paymentsuite.redsys.manager'
            - '@paymentsuite.redsys.routes'
            - '@paymentsuite.bridge'
            - '@router'
        tags:
            - { name: controller.service_arguments }
