services:

    #
    # Services
    #
    paymentsuite.redsys.manager:
        class: PaymentSuite\RedsysBundle\Services\RedsysManager
        arguments:
            - '@paymentsuite.redsys.form_type_builder'
            - '@paymentsuite.redsys.method_factory'
            - '@paymentsuite.bridge'
            - '@paymentsuite.event_dispatcher'
            - '%paymentsuite.redsys.secret_key%'

    paymentsuite.redsys.form_type_builder:
        class: PaymentSuite\RedsysBundle\Services\RedsysFormTypeBuilder
        arguments:
            - '@paymentsuite.bridge'
            - '@paymentsuite.redsys.url_factory'
            - '@form.factory'
            - '%paymentsuite.redsys.merchant_code%'
            - '%paymentsuite.redsys.secret_key%'
            - '%paymentsuite.redsys.url%'

    paymentsuite.redsys.url_factory:
        class: PaymentSuite\RedsysBundle\Services\RedsysUrlFactory
        arguments:
            - '@router'

    paymentsuite.redsys.method_factory:
        class: PaymentSuite\RedsysBundle\Services\RedsysMethodFactory
