services:

    #
    # Services
    #
    paymentsuite.redsys.manager:
        class: PaymentSuite\RedsysBundle\Services\RedsysManager
        arguments:
            - '@paymentsuite.redsys.form_type_builder'
            - '@paymentsuite.redsys.method_factory'
            - '@paymentsuite.bridge'
            - '@paymentsuite.event_dispatcher'
            - '@paymentsuite.redsys.order_transformer'

    paymentsuite.redsys.form_type_builder:
        class: PaymentSuite\RedsysBundle\Services\RedsysFormTypeBuilder
        arguments:
            - '@paymentsuite.bridge'
            - '@paymentsuite.redsys.signature_factory'
            - '@form.factory'
            - '@paymentsuite.redsys.parameters_factory'
            - '%paymentsuite.redsys.url%'

    paymentsuite.redsys.parameters_factory:
        class: PaymentSuite\RedsysBundle\Services\RedsysParametersFactory
        arguments:
            - '@paymentsuite.bridge'
            - '@paymentsuite.redsys.url_factory'
            - '@paymentsuite.redsys.order_transformer'
            - '@paymentsuite.redsys.settings_provider'
        calls:
            - [addExtension, ['@paymentsuite.redsys.psd2_parameters_extension']]

    paymentsuite.redsys.psd2_parameters_extension:
        class: PaymentSuite\RedsysBundle\Services\RedsysPsd2ParametersExtension
        arguments:
            - '@paymentsuite.bridge'

    paymentsuite.redsys.url_factory:
        class: PaymentSuite\RedsysBundle\Services\RedsysUrlFactory
        arguments:
            - '@router'

    paymentsuite.redsys.method_factory:
        class: PaymentSuite\RedsysBundle\Services\RedsysMethodFactory
        arguments:
            - '@paymentsuite.redsys.signature_factory'
            - '@paymentsuite.redsys.settings_provider'

    paymentsuite.redsys.signature_factory:
        class: PaymentSuite\RedsysBundle\Services\RedsysSignatureFactory
        arguments:
            - '@paymentsuite.redsys.settings_provider'

    paymentsuite.redsys.order_transformer:
        class: PaymentSuite\RedsysBundle\Services\RedsysOrderTransformer

    paymentsuite.redsys.settings_provider_default:
        class: PaymentSuite\RedsysBundle\Services\RedsysSettingsProviderDefault
        arguments:
            - '%paymentsuite.redsys.merchant_code%'
            - '%paymentsuite.redsys.terminal%'
            - '%paymentsuite.redsys.secret_key%'
