services:

    #
    # Controllers
    #
    paymentsuite.bankwire.payment_controller:
        class: PaymentSuite\BankwireBundle\Controller\PaymentController
        arguments:
            - "@paymentsuite.bankwire.manager"
            - "@paymentsuite.bankwire.route_success"
            - "@paymentsuite.bridge"
            - "@router"
