services:

    paymentsuite.event_dispatcher:
        class: PaymentSuite\PaymentCoreBundle\Services\PaymentEventDispatcher
        arguments:
            - @event_dispatcher

    paymentsuite.logger:
        class: PaymentSuite\PaymentCoreBundle\Services\PaymentLogger
        arguments:
            - @logger
            - %paymentsuite.logger%
        tags:
            - { name: monolog.logger, channel: 'paymentsuite' }
