services:

    safetypay.form.type.wrapper:
        class: %safetypay.form.type.wrapper.class%
        arguments:
            form.factory: @form.factory
            payment.bridge: @payment.bridge
            key: %safetypay.key%
            signature: %safetypay.signature%
            safetypay.manager: @safetypay.manager
            expiration: %safetypay.expiration%
            payment.logger: @payment.logger
        tags:
            - { name: form.type, alias: safetypay_view }

    safetypay.routes.loader:
        class: %safetypay.routes.loader.class%
        arguments:
            safetypay.controller.route: %safetypay.controller.route%
            safetypay.controller.route.name: %safetypay.controller.route.name%
            safetypay.controller.route.confirm: %safetypay.controller.route.confirm%
            safetypay.controller.route.confirm.name: %safetypay.controller.route.confirm.name%

        tags:
            - { name: routing.loader }

    safetypay.manager:
      class: %safetypay.manager.class%
      arguments:
          safetypay.response.format: %safetypay.response.format%
          safetypay.token: %safetypay.token%
          safetypay.signature: %safetypay.signature%
          payment.bridge: @payment.bridge
          payment.event.dispatcher: @payment.event.dispatcher
          key: %safetypay.key%
          payment.logger: @payment.logger
